### ISSUE TITLE
Leaving a comment in the feedback tools won't work in a narrow window

### ISSUE THREAD

**Issue by pavpanchekha** [browserengineering/book#163]

**Comment by mipsumlo** [comment]
On top of this (might be a separate issue), it's very easy to accidentally close the feedback overlay after writing text in the feedback form and losing all progress. I pinpointed the issue to [Line 263 of do_cancel](https://github.com/browserengineering/book/blob/b99aea136f23f965d4387cc6b25267d5a16e8026/www/feedback.js#L263) in feedback.js, which might be a little merciless. Suggesting 1) hiding instead of .remove(), or using temporary state of some sort until the page is refreshed (unless localStorage is of any interest for previously-submitted feedback).
